<a href="https://colab.research.google.com/github/yudhiesh1997/Optimisation-Deep-Learning/blob/master/BostonHouse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy 

In [2]:
df = pd.read_csv("/content/boston.csv")

In [3]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

In [4]:
df.isnull().sum().sum()

0

In [9]:
X = df.drop(columns="PRICE", axis=1).values
y = df["PRICE"].values

In [14]:
X.reshape(-1,1)

array([[6.320e-03],
       [1.800e+01],
       [2.310e+00],
       ...,
       [2.100e+01],
       [3.969e+02],
       [7.880e+00]])

In [15]:
y.reshape(-1,1)

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [17]:
lin_reg = LinearRegression(normalize=True, n_jobs=-1)
lin_reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=True)

In [18]:
y_pred = lin_reg.predict(X_test)

In [19]:
print(f'MSE : {mean_squared_error(y_test, y_pred)}')

MSE : 24.69755937273918


In [20]:
r2 = lin_reg.score(X_test, y_test)
print(f'R-squared : {r2:.4f}')

R-squared : 0.6943


In [21]:
print(f'Intercept (b0) : {lin_reg.intercept_}\nSlope (b1) : {lin_reg.coef_}' )

Intercept (b0) : 35.88361278171245
Slope (b1) : [-9.83985759e-02  4.45802844e-02  3.41724925e-02  2.97036448e+00
 -1.57483038e+01  4.00791161e+00 -7.66815793e-03 -1.36083558e+00
  2.95500907e-01 -1.38517521e-02 -1.00410129e+00  7.20435933e-03
 -4.81417534e-01]


In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDRegressor

parameters = {
    "loss": ("squared_loss", "huber"),
    "penalty": ('l2', 'l1', "elasticnet"),
    "alpha": [1e-6, 1e-5, 1e-4,1e-3, 1e-2, 1e-1, 1],
    "max_iter": [5000,10000, 20000]
}

sgd = SGDRegressor(random_state=42)
clf = GridSearchCV(sgd, parameters)
clf.fit(X_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SGDRegressor(alpha=0.0001, average=False,
                                    early_stopping=False, epsilon=0.1,
                                    eta0=0.01, fit_intercept=True,
                                    l1_ratio=0.15, learning_rate='invscaling',
                                    loss='squared_loss', max_iter=1000,
                                    n_iter_no_change=5, penalty='l2',
                                    power_t=0.25, random_state=42, shuffle=True,
                                    tol=0.001, validation_fraction=0.1,
                                    verbose=0, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1],
                         'loss': ('squared_loss', 'huber'),
                         'max_iter': [5000, 10000, 20000],
                         'penalty': ('l2', 'l1', 'elasticnet')},
           

In [24]:
clf.best_params_

{'alpha': 0.01, 'loss': 'huber', 'max_iter': 5000, 'penalty': 'l2'}

In [25]:
clf.best_score_

-0.27066062600980095

In [26]:
clf.best_estimator_.intercept_

array([0.02464601])

In [27]:
clf.best_estimator_.coef_

array([-7.96835179e-02,  9.53712415e-02, -1.65062417e-01,  1.45976900e-02,
        9.17092269e-03,  2.78152563e-01,  1.42456649e-01,  8.31259802e-03,
        1.20502575e-01,  1.64716478e-04,  1.70483813e-01,  9.81633130e-02,
       -5.20124003e-01])

In [28]:
y_pred = clf.predict(X_test)

In [29]:
print(f'MSE : {mean_squared_error(y_test, y_pred)}')

MSE : 541.6365625917882


## Linear Regression has a much lower MSE compared to Stochastic Gradient Descent 