## Data Preprocessing
1. Reading the file
2. Missing data
3. Drop duplicates

### Exploratory analysis

df.head() # show first 5 rows

df.tail() # last 5 rows

df.columns # list all column names

df.shape # get number of rows and columns

df.info() # additional info about dataframe

df.describe() # statistical description, only for numeric values

df['col_name'].value_counts(dropna=False) # count unique values in a column

df = df.drop_duplicates()

pd.melt() # transform columns to rows

In [2]:
# Importing the libraries
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt

In [3]:
# Importing the dataset
df = pd.read_csv('Data.csv')
df

Country   Age   Salary  Salary2 Purchased
0    France  44.0  72000.0      NaN        No
1     Spain  27.0  48000.0      NaN       Yes
2   Germany  30.0  54000.0      NaN        No
3     Spain  38.0  61000.0      NaN        No
4   Germany  40.0      NaN      NaN       Yes
5    France  35.0  58000.0      NaN       Yes
6     Spain   NaN  52000.0      NaN        No
7    France  48.0  79000.0      NaN       Yes
8   Germany  50.0  83000.0      NaN        No
9    France  37.0  67000.0      NaN       Yes
10      NaN   NaN      NaN      NaN       NaN
11   France  35.0  23000.0      NaN       Yes
12  Germany  35.0  45000.0      NaN        No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
Country      12 non-null object
Age          11 non-null float64
Salary       11 non-null float64
Salary2      0 non-null float64
Purchased    12 non-null object
dtypes: float64(3), object(2)
memory usage: 600.0+ bytes


In [5]:
df.shape

(13, 5)

In [6]:
df.describe()

Age        Salary  Salary2
count  11.000000     11.000000      0.0
mean   38.090909  58363.636364      NaN
std     7.049178  17019.240449      NaN
min    27.000000  23000.000000      NaN
25%    35.000000  50000.000000      NaN
50%    37.000000  58000.000000      NaN
75%    42.000000  69500.000000      NaN
max    50.000000  83000.000000      NaN

In [7]:
# Total missing values for each feature/column
df.isnull().sum()

Country       1
Age           2
Salary        2
Salary2      13
Purchased     1
dtype: int64

In [8]:
# Drop rows where all cells in that row is NA
df1 = df.dropna(how='all')
df1

Country   Age   Salary  Salary2 Purchased
0    France  44.0  72000.0      NaN        No
1     Spain  27.0  48000.0      NaN       Yes
2   Germany  30.0  54000.0      NaN        No
3     Spain  38.0  61000.0      NaN        No
4   Germany  40.0      NaN      NaN       Yes
5    France  35.0  58000.0      NaN       Yes
6     Spain   NaN  52000.0      NaN        No
7    France  48.0  79000.0      NaN       Yes
8   Germany  50.0  83000.0      NaN        No
9    France  37.0  67000.0      NaN       Yes
11   France  35.0  23000.0      NaN       Yes
12  Germany  35.0  45000.0      NaN        No

In [9]:
#Drop column if they only contain missing values
df1 = df1.dropna(axis=1, how='all')
df1

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
11   France  35.0  23000.0       Yes
12  Germany  35.0  45000.0        No

In [10]:
df1["Salary"].fillna(df["Salary"].mean(),inplace = True)
print(df1)

    Country   Age        Salary Purchased
0    France  44.0  72000.000000        No
1     Spain  27.0  48000.000000       Yes
2   Germany  30.0  54000.000000        No
3     Spain  38.0  61000.000000        No
4   Germany  40.0  58363.636364       Yes
5    France  35.0  58000.000000       Yes
6     Spain   NaN  52000.000000        No
7    France  48.0  79000.000000       Yes
8   Germany  50.0  83000.000000        No
9    France  37.0  67000.000000       Yes
11   France  35.0  23000.000000       Yes
12  Germany  35.0  45000.000000        No


C:\Users\raja.rajeswari\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py:3549: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [11]:
df1["Age"].fillna(df["Age"].mean(),inplace = True)
df1

C:\Users\raja.rajeswari\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py:3549: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


Country        Age        Salary Purchased
0    France  44.000000  72000.000000        No
1     Spain  27.000000  48000.000000       Yes
2   Germany  30.000000  54000.000000        No
3     Spain  38.000000  61000.000000        No
4   Germany  40.000000  58363.636364       Yes
5    France  35.000000  58000.000000       Yes
6     Spain  38.090909  52000.000000        No
7    France  48.000000  79000.000000       Yes
8   Germany  50.000000  83000.000000        No
9    France  37.000000  67000.000000       Yes
11   France  35.000000  23000.000000       Yes
12  Germany  35.000000  45000.000000        No

In [12]:
x1 = df1.iloc[:, :-1].values
x1

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 58363.63636363636],
       ['France', 35.0, 58000.0],
       ['Spain', 38.09090909090909, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0],
       ['France', 35.0, 23000.0],
       ['Germany', 35.0, 45000.0]], dtype=object)

In [13]:
y1 = df1.iloc[:, 3].values
y1

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'No'], dtype=object)

In [14]:
df1.describe()

Age        Salary
count  12.000000     12.000000
mean   38.090909  58363.636364
std     6.721127  16227.209065
min    27.000000  23000.000000
25%    35.000000  51000.000000
50%    37.500000  58181.818182
75%    41.000000  68250.000000
max    50.000000  83000.000000

In [15]:
copy_df1 = df1.copy()
del copy_df1['Purchased']
copy_df1

Country        Age        Salary
0    France  44.000000  72000.000000
1     Spain  27.000000  48000.000000
2   Germany  30.000000  54000.000000
3     Spain  38.000000  61000.000000
4   Germany  40.000000  58363.636364
5    France  35.000000  58000.000000
6     Spain  38.090909  52000.000000
7    France  48.000000  79000.000000
8   Germany  50.000000  83000.000000
9    France  37.000000  67000.000000
11   France  35.000000  23000.000000
12  Germany  35.000000  45000.000000

In [16]:
df1

Country        Age        Salary Purchased
0    France  44.000000  72000.000000        No
1     Spain  27.000000  48000.000000       Yes
2   Germany  30.000000  54000.000000        No
3     Spain  38.000000  61000.000000        No
4   Germany  40.000000  58363.636364       Yes
5    France  35.000000  58000.000000       Yes
6     Spain  38.090909  52000.000000        No
7    France  48.000000  79000.000000       Yes
8   Germany  50.000000  83000.000000        No
9    France  37.000000  67000.000000       Yes
11   France  35.000000  23000.000000       Yes
12  Germany  35.000000  45000.000000        No

In [17]:
X = copy_df1
X

Country        Age        Salary
0    France  44.000000  72000.000000
1     Spain  27.000000  48000.000000
2   Germany  30.000000  54000.000000
3     Spain  38.000000  61000.000000
4   Germany  40.000000  58363.636364
5    France  35.000000  58000.000000
6     Spain  38.090909  52000.000000
7    France  48.000000  79000.000000
8   Germany  50.000000  83000.000000
9    France  37.000000  67000.000000
11   France  35.000000  23000.000000
12  Germany  35.000000  45000.000000

In [18]:
X2 = df1.loc[:,['Country','Age','Salary']]
X2

Country        Age        Salary
0    France  44.000000  72000.000000
1     Spain  27.000000  48000.000000
2   Germany  30.000000  54000.000000
3     Spain  38.000000  61000.000000
4   Germany  40.000000  58363.636364
5    France  35.000000  58000.000000
6     Spain  38.090909  52000.000000
7    France  48.000000  79000.000000
8   Germany  50.000000  83000.000000
9    France  37.000000  67000.000000
11   France  35.000000  23000.000000
12  Germany  35.000000  45000.000000

In [19]:
Y = df1.loc[:,["Purchased"]]
Y

Purchased
0         No
1        Yes
2         No
3         No
4        Yes
5        Yes
6         No
7        Yes
8         No
9        Yes
11       Yes
12        No

In [ ]:
#df.fillna(df.mean())

In [20]:
# Importing the dataset
df = pd.read_csv('Data.csv')
df

Country   Age   Salary  Salary2 Purchased
0    France  44.0  72000.0      NaN        No
1     Spain  27.0  48000.0      NaN       Yes
2   Germany  30.0  54000.0      NaN        No
3     Spain  38.0  61000.0      NaN        No
4   Germany  40.0      NaN      NaN       Yes
5    France  35.0  58000.0      NaN       Yes
6     Spain   NaN  52000.0      NaN        No
7    France  48.0  79000.0      NaN       Yes
8   Germany  50.0  83000.0      NaN        No
9    France  37.0  67000.0      NaN       Yes
10      NaN   NaN      NaN      NaN       NaN
11   France  35.0  23000.0      NaN       Yes
12  Germany  35.0  45000.0      NaN        No

In [21]:
# Drop rows where all cells in that row is NA
df2 = df.dropna(how='all')

#Drop column if they only contain missing values
df2 = df2.dropna(axis=1, how='all')
df2

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
11   France  35.0  23000.0       Yes
12  Germany  35.0  45000.0        No

In [22]:
X = df2.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0],
       ['France', 35.0, 23000.0],
       ['Germany', 35.0, 45000.0]], dtype=object)

In [23]:
Y = df2.iloc[:, 3].values
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'No'], dtype=object)

In [24]:
# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
X

In [25]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 58363.63636363636],
       ['France', 35.0, 58000.0],
       ['Spain', 38.09090909090909, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0],
       ['France', 35.0, 23000.0],
       ['Germany', 35.0, 45000.0]], dtype=object)

In [26]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 58363.63636363636],
       [0, 35.0, 58000.0],
       [2, 38.09090909090909, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0],
       [0, 35.0, 23000.0],
       [1, 35.0, 45000.0]], dtype=object)

In [225]:
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   5.83636364e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80909091e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04],
       [  1.00000000e+00,   0.0000000

In [32]:
# Encoding the Dependent Variable
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0], dtype=int64)

In [229]:
df2.shape

(12, 4)

In [36]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(9, 3)
(3, 3)
(9,)
(3,)


In [37]:
# Feature Scaling using StandardScaler
# Standardize features by removing the mean and scaling to unit variance
from sklearn.preprocessing import StandardScaler

std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

print('Standardized X_train:' , X_train)
print('')
print('Standardized X_test:' , X_test)

Standardized X_train: [[-0.81649658 -0.55224384 -1.99099864]
 [ 1.63299316 -1.71858283 -0.59107772]
 [ 1.63299316 -0.10161287 -0.36709037]
 [-0.81649658  0.75988753  0.75284636]
 [-0.81649658  1.34305702  1.14482422]
 [ 0.40824829 -0.55224384 -0.75906823]
 [-0.81649658 -0.26065909  0.47286218]
 [ 0.40824829  1.63464177  1.36881156]
 [-0.81649658 -0.55224384 -0.03110935]]

Standardized X_test: [[ 0.40824829 -1.28120571 -0.2550967 ]
 [ 1.63299316 -0.11486672  0.13688116]
 [ 0.40824829  0.17671803 -0.01074687]]


C:\Users\raja.rajeswari\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


## Exercise

Using the boston dataset, perform the following tasks:

1. Load the boston data and rename the data as follows:    

    from sklearn.datasets import load_boston 
    
    boston = load_boston()
   
   
2. Load the boston data into pandas dataframe and rename the dataframe to data

3. Perform preprocessing

 

In [38]:
from sklearn.datasets import load_boston
boston = load_boston()

In [39]:
print(boston.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [40]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], 
      dtype='<U7')

In [307]:
#boston.target

In [43]:
# Loading data into pandas dataframe
data = pd.DataFrame(boston.data, columns = boston.feature_names)
data.head(2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   

   PTRATIO      B  LSTAT  
0     15.3  396.9   4.98  
1     17.8  396.9   9.14

In [44]:
data["PRICE"] = boston.target
data.head(2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   

   PTRATIO      B  LSTAT  PRICE  
0     15.3  396.9   4.98   24.0  
1     17.8  396.9   9.14   21.6

In [288]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
PRICE      506 non-null float64
dtypes: float64(14)
memory usage: 55.4 KB


In [45]:
# Total missing values for each feature
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
PRICE      0
dtype: int64

In [324]:
# Drop rows where all cells in that row is NA
#data = data.dropna(how='all')

#Drop column if they only contain missing values
#data = data.dropna(axis=1, how='all')

In [291]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       PRICE  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [292]:
# Target and features
Y = data["PRICE"]
X = data.drop("PRICE", axis = 1)

In [295]:
Y.head(3)

0    24.0
1    21.6
2    34.7
Name: PRICE, dtype: float64

In [296]:
X.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03

In [298]:
#Split the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(354, 13) (152, 13) (354,) (152,)


In [301]:
# Feature Scaling using StandardScaler

from sklearn.preprocessing import StandardScaler

std = StandardScaler()
X_train = std.fit_transform(x_train)
X_test = std.transform(x_test)

print('Standardized X_train:' , X_train)
print('')
print('Standardized X_test:' , X_test)

Standardized X_train: [[-0.43303012  2.03415755 -1.3884913  ..., -0.11812915  0.36732013
  -0.67469492]
 [-0.43222358 -0.48386596  0.26017463 ...,  0.07325629  0.39790096
  -0.81842134]
 [-0.43498958 -0.48386596 -1.13393965 ..., -0.35736096  0.42127935
  -1.00056967]
 ..., 
 [-0.43484114 -0.48386596 -1.27453504 ..., -0.35736096  0.42127935
  -1.06602923]
 [ 0.16061776 -0.48386596  1.04010906 ...,  0.79095171  0.41313234
   0.87498895]
 [ 0.54670406 -0.48386596  1.04010906 ...,  0.79095171  0.42127935
   1.71173285]]

Standardized X_test: [[-0.42033694 -0.48386596 -0.75655203 ...,  0.3124881   0.38030813
  -0.341705  ]
 [-0.43557346 -0.48386596 -0.97410489 ..., -0.02243643  0.41053474
   0.04678324]
 [-0.43424365 -0.48386596  0.126979   ...,  1.1737226   0.36330566
  -0.40716456]
 ..., 
 [-0.43384162 -0.48386596 -1.27453504 ..., -0.35736096  0.40545761
  -0.7074247 ]
 [ 0.70007375 -0.48386596  1.04010906 ...,  0.79095171  0.05820583
  -0.42708703]
 [-0.41649843  0.43940933 -0.77135154 .