In [36]:
import numpy as np   #numeric python
from timeit import timeit


# NumPy

[Numpy](http://www.numpy.org/) is short for _numerical python_, and provides functions that are especially useful when you have to work with large arrays and matrices of numeric data, like matrix multiplications.  

The array object class is the foundation of Numpy, and Numpy arrays are like lists in Python, except that every thing inside an array must be of the same type, like int or float. As a result, arrays provide much more efficient storage and data operations, especially as the arrays grow larger in size. However, in other ways, NumPy arrays are very similar to Python's built-in list type, but with the exception of Vectorization.

### Creating arrays

In [3]:
# Create array from lists:
lis = [[1,2,3,4,5],[6,7,8,9,10]]

ary = np.array(lis)

print(ary, type(ary))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>


### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in numpy that generate arrays of different forms. Some of the more common are:


### zeros and ones

In [13]:
np.zeros((3))

array([0., 0., 0.])

In [ ]:
np.ones((2,3,4), dtype = np.int16)

In [ ]:
np.empty( (2,3) )   

In [17]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.ones((4,3))  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### arange

In [10]:
# Large operations work too, and quickly
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [23]:
# prints the corners, mainly
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### random data

In [24]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.41396551, 0.28525797, 0.56237472],
       [0.43423849, 0.49777457, 0.11495651],
       [0.87560043, 0.47627616, 0.06204749]])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### linspace, logspace

In [27]:
# Make several equally spaced points in linear space
# linspace( start, end, difference)
np.linspace(0,np.pi,3)

array([0.        , 1.57079633, 3.14159265])

In [28]:
np.logspace(2, 3, 5, 3)


array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

### diag

In [29]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### Vectorization

In [31]:
lis = [1,2,3,4,5]

In [37]:
%time lis + lis

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 23.8 µs


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
# See the difference???
np_array = np.array(lis)
%time np_array + np_array

CPU times: user 13 µs, sys: 0 ns, total: 13 µs
Wall time: 15.3 µs


array([ 2,  4,  6,  8, 10])

In [39]:
# Doing the same using normal lists requires a loop!
%time print([x+x for x in lis])
%time print([x**2 for x in lis])

[2, 4, 6, 8, 10]
CPU times: user 1.03 ms, sys: 1.12 ms, total: 2.14 ms
Wall time: 7.46 ms
[1, 4, 9, 16, 25]
CPU times: user 249 µs, sys: 283 µs, total: 532 µs
Wall time: 526 µs


So we call operations on numpy arrays **vectorized**.  For almost all data intensive computing, we use numpy because of this feature, and because the whole scientific and numerical python stack is based on numpy.  

To explain it another way, in a spreadsheet you would add an entire column to another one by writing a formula in the first cell and autofilling the rest of the column.  Numpy allows you to do such commands in one go.  





In [42]:
array = np.array([1, 4, 5, 8], float)
print(array)
print("")
array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
print(array)

[1. 4. 5. 8.]

[[1. 2. 3.]
 [4. 5. 6.]]


## Broadcasting

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

In [44]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
M + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [46]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [47]:
np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [48]:
np.arange(3)[np.newaxis,np.newaxis]

array([[[0, 1, 2]]])

In [49]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

- **Rule 1:** If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
- **Rule 2:** If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- **Rule 3:** If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

To make these rules clear, let's consider a few examples in detail.

In [50]:
# Rule one
M = np.ones((2, 3))
a = np.arange(3)
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [51]:
# Rule two
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a,b)

[[0]
 [1]
 [2]] [0 1 2]


In [ ]:
a + b

In [52]:
# Rule three
M = np.ones((3, 2))
a = np.arange(3)
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [53]:
# To get over the problem:
a[:, np.newaxis].shape

(3, 1)

In [54]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [55]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

## Manipulating arrays
 
### Indexing
We can index elements in an array using square brackets and indices:

In [56]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])
v[0]

1

In [62]:
M = np.random.random([3,3])
print(M)
# M is a matrix, or a 2 dimensional array, taking two indices 
print(M[1,1])
print(M[1,2])

[[0.72770272 0.48509871 0.10193287]
 [0.4290032  0.59842558 0.13134373]
 [0.43771697 0.83777726 0.40299443]]
0.5984255814394024
0.1313437297333805


## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

Source: _Python Data Science Handbook_

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array)

In [63]:
M

array([[0.72770272, 0.48509871, 0.10193287],
       [0.4290032 , 0.59842558, 0.13134373],
       [0.43771697, 0.83777726, 0.40299443]])

In [64]:
M[1]

array([0.4290032 , 0.59842558, 0.13134373])

The same thing can be achieved with using : instead of an index:

In [65]:
M[1,:] #row 1

array([0.4290032 , 0.59842558, 0.13134373])

In [66]:
M[:,1] #column 1

array([0.48509871, 0.59842558, 0.83777726])

We can assign new values to elements in an array using indexing:

In [67]:
M[0,0] = 1

In [68]:
M

array([[1.        , 0.48509871, 0.10193287],
       [0.4290032 , 0.59842558, 0.13134373],
       [0.43771697, 0.83777726, 0.40299443]])

In [69]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [70]:
M

array([[ 1.        ,  0.48509871, -1.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.43771697,  0.83777726, -1.        ]])

### Index Slicing
Index slicing is the technical name for the syntax M[lower:upper:step] to extract part of an array:

In [71]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [72]:
A[1:3]

array([2, 3])

Array slices are mutable: if they are assigned a new value the original array from which the slice was extracted is modified:

In [73]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in M[lower:upper:step]:

In [74]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [75]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [76]:
A[:3] # first three elements

array([ 1, -2, -3])

In [77]:
A[3:] # elements from index 3

array([4, 5])

Index slicing works exactly the same way for multidimensional arrays:


In [78]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [79]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [80]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing
Fancy indexing is the name for when an array or list is used in-place of an index:

In [81]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [83]:
row_indices = [1, 2, 3]
# takes matrix based on rows 
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [87]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

In [88]:
A[[1],[1]]

array([11])

We can also use index masks: If the index mask is an Numpy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element:

In [90]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [92]:
row_mask = np.array([True, False, False, False, False])
B[row_mask]

array([0])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [94]:
x = np.arange(0, 10, 0.5)
# 0 - 10 with a stride of 0.5 
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [97]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [98]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

### Using arrays in conditions

When using arrays in conditions,for example ```if``` statements and other boolean expressions, one needs to use ```any``` or ```all```, which requires that any or all elements in the array evalutes to ```True```:

In [99]:
M = np.array([[ 1,  4],[ 9, 16]])
M

array([[ 1,  4],
       [ 9, 16]])

In [21]:
#any
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

at least one element in M is larger than 5


In [100]:
#all
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("not all elements in M are larger than 5")

not all elements in M are larger than 5


## Functions for extracting data from arrays and creating arrays

**where**

The index mask can be converted to position index using the where function

In [101]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [102]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]


array([5.5, 6. , 6.5, 7. ])

**diag**

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [103]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [104]:
np.diag(A, -1)

array([10, 21, 32, 43])

**take**

The take function is similar to fancy indexing described above:

In [105]:
v2 = np.arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [106]:
row_indices = [1, 3, 5]
v2[row_indices] # fancy indexing

array([-2,  0,  2])

In [107]:
v2.take(row_indices)

array([-2,  0,  2])

But take also works on lists and other objects:


In [108]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

array([-2,  0,  2])

**choose**

Constructs an array by picking elements from several arrays:

In [109]:
which = [1, 0, 1, 0]
choices = [[-2,-2,-2,-2], [5,5,5,5]]

np.choose(which, choices)

array([ 5, -2,  5, -2])

In [110]:
np.choose?

## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations
We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [111]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [34]:
v1 * 2

array([0, 2, 4, 6, 8])

In [112]:
v1 + 2

array([2, 3, 4, 5, 6])

In [113]:
A*2

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [114]:
print(A * 2)
print(A + 2)

[[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]
[[ 2  3  4  5  6]
 [12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]]


### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is element-wise operations:

In [115]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [116]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:


In [117]:
A.shape, v1.shape

((5, 5), (5,))

In [118]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

### Matrix algebra

What about matrix mutiplication? There are two ways. We can either use the dot function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments:

In [119]:
np.dot(A,A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [120]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [121]:
np.dot(v1,v1)

30

Alternatively, we can cast the array objects to the type matrix. This changes the behavior of the standard arithmetic operators +, -, * to use matrix algebra.

In [122]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector

In [123]:
M

matrix([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])

In [124]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [125]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [126]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:


In [127]:
v = np.matrix([1,2,3,4,5,6]).T

In [128]:
np.shape(M), np.shape(v)

((5, 5), (6, 1))

In [52]:
M * v #error due to different dimension

ValueError: shapes (5,5) and (6,1) not aligned: 5 (dim 1) != 6 (dim 0)

## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 


### Attributes of Numpy Arrays

In [129]:
# Create a ranged array: 
# arange = array range
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [130]:
# reshape it
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
# You can specify the type of an array:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [132]:
ndarray = np.array([[1,2,3],[4,5,6]])
type(ndarray), ndarray

(numpy.ndarray, array([[1, 2, 3],
        [4, 5, 6]]))

In [133]:
# Number of axes or dimensions of the array (also called rank)
ndarray.ndim

2

In [134]:
# Dimensions of the array:
# For a matrix with n rows and m columns, 
# shape will be (n,m).
ndarray.shape

(2, 3)

In [135]:
# Type of elements in the array
ndarray.dtype

dtype('int64')

In [136]:
# Size in bytes of each element of the array
# int64 has itemsize 8
# complex32 has itemsize 4
print("itemsize:", ndarray.itemsize, "bytes")
print("nbytes:", ndarray.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 48 bytes


### Adding a new dimension: newaxis

With newaxis, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:

In [137]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [138]:
np.shape(v)

(3,)

In [139]:
# make a column matrix of the vector v
v[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [140]:
# column matrix
v[:,np.newaxis].shape

(3, 1)

In [141]:
v[np.newaxis,:].shape

(1, 3)

### Array Concatenation and splitting

In [142]:
# Try the following
# np.concatenate (axis = 1)
A = np.arange(10)
B = np.arange(30, 55)
print('A')
print(A)
print('B')
print(B)
# np.concatenate
# np.split
# np.hstack
# np.vstack
# np.dstack
# np.floor
# np.hsplit
# np.vsplit
# np.dsplit

A
[0 1 2 3 4 5 6 7 8 9]
B
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54]


In [68]:
np.vstack([A, np.arange(20, 40).reshape((2,10))])
# stacks the arrays 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [69]:
np.dstack([A,A])
# two columns of matrix 

array([[[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]]])

In [143]:
np.hsplit?

## **Exercises:**


1. Create a 3x3 matrix with values ranging from 0 to 8
2. Create a 10x10 array with random values and find the minimum and maximum values
3. Create a 8x8 matrix and fill it with a checkerboard pattern 
3. Create random vector of size 10 and replace the maximum value by 0
4. Create a $4 * 4$ identity matrix.
6. Generate a random $4 \times 4 \times 4$ array of Gaussianly distributed numbers.   
7. Generate `n` evenly spaced intervals between 0. and 1.  
8. Create a vector and then reverse the vector (first element becomes last)

Looking for more?  Checkout  the Neophyte, Novice, and  Apprentice levels [here](http://www.loria.fr/~rougier/teaching/numpy.100/).

In [145]:
# 1
np.arange(0, 9, ).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
# 2
rand = np.random.rand(10,10)
arr = np.array(rand)
print("Max of array is :", np.max(arr))
print("Min of array is :", np.min(arr))

Max of array is : 0.9920737589199365
Min of array is : 0.007645199821759263


In [151]:
# 3
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2
checkerboard((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [162]:
# 4
x = np.random.random(10)
result = np.where(x == np.amax(x))
# max at index 6 
x[result] = 0
x

array([0.67616475, 0.62825371, 0.76122314, 0.        , 0.12526847,
       0.31765069, 0.03560756, 0.41604016, 0.83244886, 0.7608839 ])

In [163]:
# 5 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [164]:
# 6
np.random.normal(0, 1, (4,4,4))

array([[[ 1.76689877,  1.66739719,  2.25332946, -0.68601302],
        [ 0.95146846, -0.03500987,  0.9363971 ,  0.47909157],
        [-0.05068537, -1.52747907,  1.164153  , -0.15417079],
        [-0.44277051,  0.45869141,  0.61621861, -1.04504602]],

       [[ 0.52451949, -2.94763214, -0.45299795,  1.77856834],
        [ 0.71022937, -1.75061879, -1.76394718,  1.7226624 ],
        [ 2.70379092, -0.58676092, -0.61468747, -1.07614395],
        [-0.4225646 , -0.50108788, -1.59763176, -0.41200038]],

       [[ 0.28314804, -0.72461607,  0.45082404, -0.41868655],
        [ 0.27128649,  0.88214973,  1.42328113, -0.4276335 ],
        [ 0.87979283, -0.309787  , -0.39954051, -0.46045654],
        [-0.65527297,  0.16755453, -0.51918701, -0.34402477]],

       [[-1.34147275,  0.18485966, -0.43456351,  0.92159447],
        [-1.61117693, -0.61698022, -1.06051773, -0.17342115],
        [-2.00537488,  2.16522211, -1.90190621, -1.69365991],
        [ 0.10440217,  1.1020804 ,  0.30206255, -1.34184775]]])

In [166]:
# 7
def even_space(n):
    return np.linspace(0,1, (n))
even_space(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [174]:
# 8
x = np.random.rand(10)
# x[::-1]
x

array([0.76410522, 0.00307036, 0.11978457, 0.60307754, 0.12477701,
       0.61067452, 0.00597639, 0.10570992, 0.84023406, 0.42906876])

In [175]:
x[::-1]

array([0.42906876, 0.84023406, 0.10570992, 0.00597639, 0.61067452,
       0.12477701, 0.60307754, 0.11978457, 0.00307036, 0.76410522])

### Other aggregation functions

NumPy provides many other aggregation functions, but we won't discuss them in detail here.
Additionally, most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point ``NaN`` value (for a fuller discussion of missing data, see [Handling Missing Data](03.04-Missing-Values.ipynb)).
Some of these ``NaN``-safe functions were not added until NumPy 1.8, so they will not be available in older NumPy versions.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

Source: Python Data Science Handbook

In [7]:
lis = [[1,2,3,4,5]]

In [8]:
np.sum(lis)

15